version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run: npm run test

workflows:
  version: 2
  build:
    jobs:
      - build
